version: '3'
services:
  server:
    build:
      context: ./server
    ports:
      - "3000:3000"
  client:
    build:
      context: ./client
    ports:
      - "4500:4500"
    depends_on:
      - server
